server:
  port: 8083

spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb+srv://adhi:honey@dbtts.fvihxmj.mongodb.net/db_transaction_service?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Konfigurasi JWT, harus SAMA PERSIS dengan service lain
jwt:
  secret: MySecretKeyIsVeryLongAndSecureAndRandom_ChangeThisPlease1234567890
  expiration:
    ms: 86400000 # 24 jam