spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: station-schedule-service-schedules
          uri: lb://station-schedule-service
          predicates:
            - Path=/schedule/**
        - id: station-schedule-service-stations
          uri: lb://station-schedule-service
          predicates:
            - Path=/station/**
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8800
