server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: station-schedule-service
          uri: lb://station-schedule-service
          predicates:
            - Path=/station/**
            - Path=/schedule/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
