
server:
  port: 8081

spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/db_user_service
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: MySecretKeyIsVeryLongAndSecureAndRandom_ChangeThisPlease1234567890
  expiration:
    ms: 86400000 # 24 jam dalam milidetik