# Konfigurasi port server untuk user-service
server:
  port: 8081

spring:
  application:
    name: user-service
  spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/db_user_service
    username: root
    password: "" # password Anda
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialek standar untuk MySQL

# Konfigurasi untuk mendaftar ke Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# --- BAGIAN PENTING UNTUK JWT ---
jwt:
  secret: MySecretKeyIsVeryLongAndSecureAndRandom_ChangeThisPlease1234567890
  expiration:
    ms: 86400000 # 24 jam dalam milidetik