server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kereta_station
    username: postgres
    password: 091717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: station-schedule-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
